name: iperf3
version: "0.1.0"
slug: iperf3
description: "iperf3 server for Home Assistant"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ports:
  "5201/tcp": 5201
  "5201/udp": 5201
options: {}
schema: {}
